In [1]:
#forward filling and backward filling
import pandas as pd
import numpy as np
time_df=pd.DataFrame({
    "Day": [1, 2, 3, 4, 5],
    "Temperature": [np.nan, 30, np.nan, 32, 35]
})
display(time_df)
print("Forward fill:")
display(time_df.ffill())
print("Backward fill:")
display(time_df.bfill())

   Day  Temperature
0    1          NaN
1    2         30.0
2    3          NaN
3    4         32.0
4    5         35.0

Forward fill:

   Day  Temperature
0    1          NaN
1    2         30.0
2    3         30.0
3    4         32.0
4    5         35.0

Backward fill:

   Day  Temperature
0    1         30.0
1    2         30.0
2    3         32.0
3    4         32.0
4    5         35.0

In [2]:
#duplicated
df = pd.read_csv(r"C:\Users\chipp\Downloads\Student_Performance.csv")
print("Duplicated rows:", df.duplicated().sum())
print("Duplicated records:")
display(df[df.duplicated(keep=False)])
df_no_duplicates = df.drop_duplicates()
print("Shape after removing duplicates:", df_no_duplicates.shape)

Duplicated rows: 1
Duplicated records:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
11,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

Shape after removing duplicates: (60, 13)

In [3]:
#data types
print(df.dtypes)

Student_ID            int64
Name                    str
Age                   int64
Gender                  str
Department              str
Attendance          float64
Study_Hours         float64
Assignment_Score      int64
Exam_Score            int64
City                    str
Enrollment_Date         str
Fee_Status              str
Placement_Status        str
dtype: object

In [4]:
#converting data types
demo = pd.DataFrame({
    "Marks": ["80", "92", "invalid", "75"]
})
demo["Marks"] = pd.to_numeric(demo["Marks"], errors="coerce")
print(demo)
print(demo.dtypes)

   Marks
0   80.0
1   92.0
2    NaN
3   75.0
Marks    float64
dtype: object

In [5]:
#string operations
names = pd.Series(["Ravi", "PRIYA", "Arun", "Meena"])
print("Clean spaces:")
print(names.str.strip())
print("\nLowercase:")
print(names.str.strip().str.lower())
print("\nTitle case:")
print(names.str.strip().str.title())

Clean spaces:
0     Ravi
1    PRIYA
2     Arun
3    Meena
dtype: str

Lowercase:
0     ravi
1    priya
2     arun
3    meena
dtype: str

Title case:
0     Ravi
1    Priya
2     Arun
3    Meena
dtype: str

In [6]:
#clean text in data set
clean = df.copy()

clean["Name"] = clean["Name"].str.strip().str.title()
clean["Department"] = clean["Department"].str.strip().str.title()

clean["Department"] = clean["Department"].replace({
    "Ai": "AI",
    "Data Science": "Data Science",
    "Python": "Python",
    "Cloud": "Cloud"
})
display(clean[["Name", "Department"]].head(15))

      Name    Department
0     Ravi  Data Science
1    Priya         Cloud
2     Arun        Python
3    Meena  Data Science
4    Kiran            AI
5   Suresh            AI
6   Anjali            AI
7    Rahul            AI
8    Divya  Data Science
9    Rahul        Python
10   Sneha            AI
11   Manoj         Cloud
12   Kavya        Python
13  Naveen  Data Science
14   Pooja            AI

In [7]:
#serching the stringwith constains
ai_students = clean[
    clean["Department"].str.contains("AI", case=False, na=False)
]
display(ai_students[["Name", "Department", "Exam_Score"]])

       Name Department  Exam_Score
4     Kiran         AI          76
5    Suresh         AI          77
6    Anjali         AI          74
7     Rahul         AI          91
10    Sneha         AI          94
14    Pooja         AI          96
15   Harish         AI          66
16   Swathi         AI          91
19    Rohit         AI          70
21    Varun         AI          88
22     Asha         AI          84
26    Sneha         AI          57
29    Nisha         AI          61
31  Deepika         AI          82
32   Pranav         AI          53
36   Ganesh         AI          80
37   Shreya         AI          84
40   Rakesh         AI          99
42  Karthik         AI          97
44    Surya         AI          80
46    Manoj         AI          86
49  Sravani         AI          70
56   Venkat         AI          64
57  Sahithi         AI          56
58    Akash         AI          99
59  Madhavi         AI          99

In [8]:
#date and time
date_df = clean.copy()
date_df["Enrollment_Date"] = pd.to_datetime(
    date_df["Enrollment_Date"]
)
date_df["Enrollment_Year"] = date_df["Enrollment_Date"].dt.year
date_df["Enrollment_Month"] = date_df["Enrollment_Date"].dt.month
date_df["Enrollment_Day"] = date_df["Enrollment_Date"].dt.day
display(date_df[["Enrollment_Date", "Enrollment_Year", "Enrollment_Month", "Enrollment_Day"]].head())

  Enrollment_Date  Enrollment_Year  Enrollment_Month  Enrollment_Day
0      2026-01-05             2026                 1               5
1      2026-01-08             2026                 1               8
2      2026-01-11             2026                 1              11
3      2026-01-14             2026                 1              14
4      2026-01-17             2026                 1              17

In [9]:
#groupby
dept_avg = (
    clean.groupby("Department")["Exam_Score"]
    .mean()
    .sort_values(ascending=False)
)
display(dept_avg)

Department
Cloud           87.900000
AI              79.769231
Python          78.857143
Data Science    76.882353
Name: Exam_Score, dtype: float64

In [39]:
#GroupBy with multiple aggregations
summary = (
    clean.groupby("Department")["Exam_Score"]
    .agg(["count", "mean", "min", "max"])
    .round(2)
)

display(summary)

              count   mean  min  max
Department
AI               26  79.77   53   99
Cloud            10  87.90   72   99
Data Science     17  76.88   54   99
Python            7  78.86   59   98

In [40]:
#GroupBy using multiple columns
multi_group = (
    clean.groupby(["Department", "Gender"])["Exam_Score"]
    .mean()
    .round(2)
)

display(multi_group)

Department    Gender
AI            Female    80.70
              Male      79.19
Cloud         Female    91.00
              Male      85.83
Data Science  Female    72.71
              Male      79.80
Python        Female    80.67
              Male      77.50
Name: Exam_Score, dtype: float64

In [41]:
# Merge
students = clean[["Student_ID", "Name", "Department"]].copy()

attendance = clean[["Student_ID", "Attendance"]].copy()

merged = pd.merge(
    students,
    attendance,
    on="Student_ID",
    how="inner"
)

display(merged.head())

   Student_ID   Name    Department  Attendance
0        1001   Ravi  Data Science        84.0
1        1002  Priya         Cloud        76.1
2        1003   Arun        Python        98.9
3        1004  Meena  Data Science        97.9
4        1005  Kiran            AI         NaN

In [42]:
#Merge types
left_demo = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

right_demo = pd.DataFrame({
    "ID": [2, 3, 4],
    "Score": [80, 90, 70]
})

print("Inner:")
display(pd.merge(left_demo, right_demo, on="ID", how="inner"))

print("Left:")
display(pd.merge(left_demo, right_demo, on="ID", how="left"))

print("Outer:")
display(pd.merge(left_demo, right_demo, on="ID", how="outer"))

Inner:

   ID Name  Score
0   2    B     80
1   3    C     90

Left:

   ID Name  Score
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0

Outer:

   ID Name  Score
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
3   4  NaN   70.0

In [43]:
# Concatenate
part1 = clean.iloc[:5][["Student_ID", "Name", "Exam_Score"]]
part2 = clean.iloc[5:10][["Student_ID", "Name", "Exam_Score"]]

combined_rows = pd.concat([part1, part2], axis=0, ignore_index=True)
display(combined_rows)

   Student_ID    Name  Exam_Score
0        1001    Ravi          78
1        1002   Priya          99
2        1003    Arun          70
3        1004   Meena          64
4        1005   Kiran          76
5        1006  Suresh          77
6        1007  Anjali          74
7        1008   Rahul          91
8        1009   Divya          77
9        1010   Rahul          84

In [38]:
#Pivot table
pivot = pd.pivot_table(
    clean,
    values="Exam_Score",
    index="Department",
    columns="Gender",
    aggfunc="mean"
).round(2)

display(pivot)

Gender        Female   Male
Department
AI             80.70  79.19
Cloud          91.00  85.83
Data Science   72.71  79.80
Python         80.67  77.50

In [37]:
# Descriptive statistics

scores = clean["Exam_Score"]

print("Mean:", scores.mean())
print("Median:", scores.median())
print("Mode:", scores.mode().tolist())
print("Minimum:", scores.min())
print("Maximum:", scores.max())
print("Standard deviation:", round(scores.std(), 2))

Mean: 80.14754098360656
Median: 80.0
Mode: [99]
Minimum: 53
Maximum: 99
Standard deviation: 14.47

In [36]:
# Correlation
correlation = clean[
    ["Attendance", "Study_Hours", "Assignment_Score", "Exam_Score"]
].corr()

display(correlation.round(2))

                  Attendance  Study_Hours  Assignment_Score  Exam_Score
Attendance              1.00         0.00             -0.03        0.06
Study_Hours             0.00         1.00              0.08        0.83
Assignment_Score       -0.03         0.08              1.00        0.46
Exam_Score              0.06         0.83              0.46        1.00

In [35]:
# Outliers using IQR
scores = clean["Exam_Score"].dropna()

Q1 = scores.quantile(0.25)
Q3 = scores.quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = clean[
    (clean["Exam_Score"] < lower) |
    (clean["Exam_Score"] > upper)
]

print("Lower limit:", lower)
print("Upper limit:", upper)
print("Number of outliers:", len(outliers))
display(outliers[["Name", "Exam_Score"]])

Lower limit: 32.5
Upper limit: 132.5
Number of outliers: 0

Empty DataFrame
Columns: [Name, Exam_Score]
Index: []

In [34]:
#sampling()
print("Random sample:")
display(clean.sample(5, random_state=42))

print("10% sample:")
display(clean.sample(frac=0.10, random_state=42))

Random sample:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
13,1014,Naveen,23,Male,Data Science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed

10% sample:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
13,1014,Naveen,23,Male,Data Science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed

In [ ]:
#apply()
def grade(score):
    if score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 50:
        return "C"
    else:
        return "F"

apply_demo = clean[["Name", "Exam_Score"]].copy()
apply_demo["Grade"] = apply_demo["Exam_Score"].apply(grade)

display(apply_demo.head(10))

     Name  Exam_Score Grade
0    Ravi          78     B
1   Priya          99     A
2    Arun          70     B
3   Meena          64     C
4   Kiran          76     B
5  Suresh          77     B
6  Anjali          74     B
7   Rahul          91     A
8   Divya          77     B
9   Rahul          84     B

In [33]:
#map()
status_map = {
    "Paid": 1,
    "Pending": 0
}

map_demo = clean[["Name", "Fee_Status"]].copy()
map_demo["Fee_Status_Code"] = map_demo["Fee_Status"].map(status_map)

display(map_demo.head(10))

     Name Fee_Status  Fee_Status_Code
0    Ravi       Paid                1
1   Priya       Paid                1
2    Arun       Paid                1
3   Meena       Paid                1
4   Kiran       Paid                1
5  Suresh       Paid                1
6  Anjali       Paid                1
7   Rahul    Pending                0
8   Divya       Paid                1
9   Rahul       Paid                1

In [32]:
#replace()
replace_demo = pd.Series(["AI", "ai", "Data Science", "DS", "AI"])

replace_demo = replace_demo.replace({
    "ai": "AI",
    "DS": "Data Science"
})

print(replace_demo)

0              AI
1              AI
2    Data Science
3    Data Science
4              AI
dtype: str

In [31]:
#Unique values and value counts
print("Cities:")
print(clean["City"].unique())

print("\nNumber of cities:")
print(clean["City"].nunique())

print("\nStudents by city:")
print(clean["City"].value_counts())

Cities:
<StringArray>
['Visakhapatnam', 'Chennai', 'Hyderabad', 'Vijayawada', 'Bengaluru']
Length: 5, dtype: str

Number of cities:
5

Students by city:
City
Hyderabad        15
Bengaluru        14
Chennai          13
Visakhapatnam    12
Vijayawada        7
Name: count, dtype: int64

In [30]:
# Data-quality checks
print("Missing values:")
display(clean.isna().sum())

print("Duplicate rows:", clean.duplicated().sum())

print("Attendance outside 0-100:")
display(clean[(clean["Attendance"] < 0) | (clean["Attendance"] > 100)])

print("Exam scores outside 0-100:")
display(clean[(clean["Exam_Score"] < 0) | (clean["Exam_Score"] > 100)])

Missing values:

Student_ID          0
Name                0
Age                 0
Gender              0
Department          1
Attendance          2
Study_Hours         2
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

Duplicate rows: 1
Attendance outside 0-100:

Empty DataFrame
Columns: [Student_ID, Name, Age, Gender, Department, Attendance, Study_Hours, Assignment_Score, Exam_Score, City, Enrollment_Date, Fee_Status, Placement_Status]
Index: []

Exam scores outside 0-100:

Empty DataFrame
Columns: [Student_ID, Name, Age, Gender, Department, Attendance, Study_Hours, Assignment_Score, Exam_Score, City, Enrollment_Date, Fee_Status, Placement_Status]
Index: []

In [29]:
#omplete data-cleaning workflow
clean_df = df.copy()

# 1. Remove exact duplicates
clean_df = clean_df.drop_duplicates()

# 2. Clean text
clean_df["Name"] = clean_df["Name"].str.strip().str.title()
clean_df["Department"] = clean_df["Department"].str.strip().str.title()

# 3. Standardize categories
clean_df["Department"] = clean_df["Department"].replace({
    "Ai": "AI"
})

# 4. Convert types
clean_df["Enrollment_Date"] = pd.to_datetime(
    clean_df["Enrollment_Date"],
    errors="coerce"
)

clean_df["Attendance"] = pd.to_numeric(
    clean_df["Attendance"],
    errors="coerce"
)

clean_df["Study_Hours"] = pd.to_numeric(
    clean_df["Study_Hours"],
    errors="coerce"
)

# 5. Handle missing numerical values
for col in ["Attendance", "Study_Hours"]:
    clean_df[col] = clean_df[col].fillna(clean_df[col].median())

# 6. Handle missing categorical value
clean_df["Department"] = clean_df["Department"].fillna("Unknown")

# 7. Validate
print("Shape:", clean_df.shape)
print("\nMissing values:")
print(clean_df.isna().sum())
print("\nDuplicates:", clean_df.duplicated().sum())

display(clean_df.head())

Shape: (60, 13)

Missing values:
Student_ID          0
Name                0
Age                 0
Gender              0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

Duplicates: 0

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,85.4,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed

In [28]:
# Encoding categorical data
encoded = pd.get_dummies(
    clean_df,
    columns=["Gender", "Department", "City", "Fee_Status"],
    dtype=int
)

display(encoded.head())
print("Encoded shape:", encoded.shape)

,Student_ID,Name,Age,Attendance,Study_Hours,Assignment_Score,Exam_Score,Enrollment_Date,Placement_Status,Gender_Female,...,Department_Data Science,Department_Python,Department_Unknown,City_Bengaluru,City_Chennai,City_Hyderabad,City_Vijayawada,City_Visakhapatnam,Fee_Status_Paid,Fee_Status_Pending
0,1001,Ravi,21,84.0,5.5,63,78,2026-01-05,Placed,1,...,1,0,0,0,0,0,0,1,1,0
1,1002,Priya,23,76.1,8.4,61,99,2026-01-08,Placed,0,...,0,0,0,0,1,0,0,0,1,0
2,1003,Arun,23,98.9,2.0,63,70,2026-01-11,Placed,1,...,0,1,0,0,0,1,0,0,1,0
3,1004,Meena,21,97.9,3.6,72,64,2026-01-14,Not Placed,0,...,1,0,0,0,0,0,0,1,1,0
4,1005,Kiran,22,85.4,2.8,70,76,2026-01-17,Placed,0,...,0,0,0,0,0,0,1,0,1,0

Encoded shape: (60, 23)